### PR TITLE
Updated zombienet instructions to include NPM and MacOS install instructions.

### PR DESCRIPTION
**Pull request by shawntabrizi**
evidence can be found here: https://github.com/paritytech/zombienet/pull/1842

There is no additional context needed for this submission, but if there was, I would write about it here.

Remember to include your reward address!

polkadot address: 12hAtDZJGt4of3m2GqZcUCVAjZPALfvPwvtUTFZPQUbdX1Ud

### CODE REVIEW

**Comment by shawntabrizi** [comment]
Good bot :)

**Comment by KarimJedda** [comment]
I tip my hat to you, kind bot

**Comment by iammasterbrucewayne** [comment]
The link on the proposal is broken, pointing to https://github.com/paritytech/bounties/pull/1

**Comment by KarimJedda** [comment]
@mutantcornholio FYI

**Comment by mutantcornholio** [comment]
> @mutantcornholio FYI

https://github.com/paritytech/substrate-tip-bot/issues/178

**Pull request merged**
